name: TEST

on: [push]

env:
  APP_ENV: TEST

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Test & Check coverage
        env:
          TEST_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          TEST_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TEST_DB_HOST: ${{ secrets.DB_HOST }}
          TEST_DB_PORT: ${{ secrets.DB_PORT }}
          TEST_DB_NAME: ${{ secrets.DB_NAME }}
        run: coverage run --source=backend -m pytest -v backend/tests
